version: '3.8'

services:
  webapp:
    build:
      context: ./React_project.Server  # Define o diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile  # Caminho para o Dockerfile relativo ao contexto
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=mydb;User=sa;Password=ComplexPassword123!;

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "ComplexPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
